// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebEFMigration.Model;

namespace WebEFMigration.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20181115131722_v5.1")]
    partial class v51
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebEFMigration.Model.Blog", b =>
                {
                    b.Property<int>("NameID");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Url");

                    b.HasKey("NameID");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("WebEFMigration.Model.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlogID");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("BlogID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("WebEFMigration.Model.Post", b =>
                {
                    b.HasOne("WebEFMigration.Model.Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
