// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebEFMigration.Model;

namespace WebEFMigration.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20181115145825_v5.3")]
    partial class v53
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebEFMigration.Model.Blog", b =>
                {
                    b.Property<int>("NameID");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Url");

                    b.HasKey("NameID");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("WebEFMigration.Model.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LicensePlate")
                        .IsRequired();

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.HasKey("CarId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("WebEFMigration.Model.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlogID");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("BlogID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("WebEFMigration.Model.RecordOfSale", b =>
                {
                    b.Property<int>("RecordOfSaleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CarLicensePlate");

                    b.Property<DateTime>("DateSold");

                    b.Property<decimal>("Price");

                    b.HasKey("RecordOfSaleId");

                    b.HasIndex("CarLicensePlate");

                    b.ToTable("RecordOfSale");
                });

            modelBuilder.Entity("WebEFMigration.Model.Post", b =>
                {
                    b.HasOne("WebEFMigration.Model.Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebEFMigration.Model.RecordOfSale", b =>
                {
                    b.HasOne("WebEFMigration.Model.Car", "Car")
                        .WithMany("SaleHistory")
                        .HasForeignKey("CarLicensePlate")
                        .HasPrincipalKey("LicensePlate");
                });
#pragma warning restore 612, 618
        }
    }
}
